# Generated by Django 6.0.6 on 2026-07-09 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SCHEDULED', 'Scheduled'), ('REFERRED', 'Referred'), ('LOCKED', 'Locked'), ('NEEDS_DOCTOR_ATTENTION', 'Needs Doctor Attention'), ('NEEDS_MIDWIFE_ATTENTION', 'Needs Midwife Attention'), ('NEEDS_NUTRITIONIST_ATTENTION', 'Needs Nutritionist Attention'), ('NEEDS_LAB_ATTENTION', 'Needs Lab Attention'), ('NEEDS_THERAPIST_ATTENTION', 'Needs Therapist Attention'), ('COMPLETED', 'Completed'), ('REVIEWED', 'Reviewed')], default='REQUESTED', max_length=35)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_appointments', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_sent', to=settings.AUTH_USER_MODEL)),
                ('referred_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_role', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('PROFILE_CREATED', 'Profile Created'), ('VITALS_ADDED', 'Vitals Added'), ('VITALS_UPDATED', 'Vitals Updated'), ('VITALS_DELETED', 'Vitals Deleted'), ('APPOINTMENT_REQUESTED', 'Appointment Requested'), ('APPOINTMENT_SCHEDULED', 'Appointment Scheduled'), ('APPOINTMENT_COMPLETED', 'Appointment Completed'), ('CASE_LOCKED', 'Case Locked'), ('CASE_REFERRED', 'Case Referred'), ('STAFF_REGISTERED', 'Staff Registered'), ('STAFF_APPROVED', 'Staff Approved'), ('NOTE_ADDED', 'Note Added'), ('CONTACT_MESSAGE_SENT', 'Contact Message Sent')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('prescriptions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='staff.appointment')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_notes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
