from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PregnancyProfileViewSet, HealthLogViewSet

# Create a router and register our viewsets with it
router = DefaultRouter()
router.register(r'pregnancy-profiles', PregnancyProfileViewSet, basename='pregnancy-profile')
router.register(r'health-logs', HealthLogViewSet, basename='health-log')

urlpatterns = [
    # This includes all the routes automatically generated by the router
    path('', include(router.urls)),
]