# Generated by Django 6.0.6 on 2026-07-09 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blood_pressure', models.CharField(help_text='Format: 120/80', max_length=20)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='In Celsius', max_digits=4, null=True)),
                ('fetal_kick_count', models.IntegerField(blank=True, null=True)),
                ('symptom', models.CharField(blank=True, choices=[('NAUSEA', 'Nausea/Morning Sickness'), ('BACK_PAIN', 'Back Pain'), ('SWOLLEN_FEET', 'Swollen Feet'), ('HEADACHE', 'Headache'), ('FATIGUE', 'Fatigue'), ('DIZZINESS', 'Dizziness'), ('HEARTBURN', 'Heartburn'), ('CONSTIPATION', 'Constipation'), ('CRAMPING', 'Cramping'), ('SHORTNESS_OF_BREATH', 'Shortness of Breath'), ('INSOMNIA', 'Insomnia'), ('FREQUENT_URINATION', 'Frequent Urination'), ('OTHER', 'Other')], max_length=25, null=True)),
                ('symptom_other', models.TextField(blank=True, help_text='Describe if symptom is Other', null=True)),
                ('mood', models.CharField(blank=True, choices=[('HAPPY', 'Happy'), ('SAD', 'Sad'), ('TIRED', 'Tired'), ('STRESSED', 'Stressed')], max_length=10, null=True)),
                ('urgent_attention_requested', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PregnancyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('last_menstrual_period_date', models.DateField()),
                ('current_week', models.IntegerField(help_text='How many weeks pregnant currently')),
                ('estimated_due_date', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(max_length=10)),
                ('existing_conditions', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medical_history_notes', models.TextField(blank=True, null=True)),
                ('is_profile_complete', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
