# Generated by Django 6.0.6 on 2026-07-06 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('blood_pressure', models.CharField(help_text='Format: 120/80', max_length=20)),
                ('fetal_kick_count', models.IntegerField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('urgent_attention_requested', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PregnancyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_menstrual_period_date', models.DateField()),
                ('estimated_due_date', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(max_length=10)),
                ('medical_history_notes', models.TextField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
