# Generated by Django 6.0.6 on 2026-06-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthlog',
            name='urgent_attention_requested',
            field=models.BooleanField(default=False),
        ),
    ]
